/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package formclient;

import model.Model_User_Account;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author ADMIN
 */
public class Home extends javax.swing.JLayeredPane {

    private Chat chat;
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        init();
    }
    
    private void init() {
        setLayout(new MigLayout("fillx, filly", "0[]1[]1[]0", "0[fill]0"));
        this.add(new Menu_Left());
        chat = new Chat();
        this.add(chat);
        this.add(new Menu_Right());
        chat.setVisible(false);
    }
    
    public void setUser(Model_User_Account user) {
        chat.setUser(user);
        chat.setVisible(true);
    }
    
    public void updateUser(Model_User_Account user) {
        chat.updateUser(user);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(java.awt.SystemColor.activeCaption);
        setPreferredSize(new java.awt.Dimension(800, 500));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
