/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package component;

import java.awt.Color;
import javax.swing.Icon;

/**
 *
 * @author ADMIN
 */
public class ChatLeft_Profile extends javax.swing.JLayeredPane {

    /**
     * Creates new form ChatLeft
     */
    public ChatLeft_Profile() {
        initComponents();
        txt.setBackground(new Color(64, 128, 209));
    }

    public void setText(String text) {

        if (text.equals("")) {
            txt.hideText();
        } else {
            txt.setText(text);
            //txt.sendSuccess();
        }
    }

    public void setUserProfile(String user) {
        txt.setUserProfile(user);
    }

    public void setImageProfile(Icon image) {
        avtimage.setImage(image);
    }

    //Anh ro
    public void setImage(Icon... image) {
        txt.setImage(false, image);
    }

    //Anh mo
    public void setImage(String... image) {
        txt.setImage(false, image);
    }

    public void setTime() {
        txt.setTime("10:30 AM");
    }
    
    public void setFile(String fileName, String fileSize) {
        txt.setFile(fileName, fileSize);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        avtimage = new swing.ImageAvatar();
        txt = new component.ChatItem();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        avtimage.setBorderSize(0);
        avtimage.setImage(new javax.swing.ImageIcon(getClass().getResource("/icon/testing/lamelo.png"))); // NOI18N
        avtimage.setMaximumSize(new java.awt.Dimension(31, 31));
        avtimage.setMinimumSize(new java.awt.Dimension(31, 31));
        avtimage.setPreferredSize(new java.awt.Dimension(31, 31));

        jLayeredPane1.setLayer(avtimage, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(avtimage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(avtimage, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(jLayeredPane1);
        add(txt);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.ImageAvatar avtimage;
    private javax.swing.JLayeredPane jLayeredPane1;
    private component.ChatItem txt;
    // End of variables declaration//GEN-END:variables
}
